# 本次构建要生成的exe文件
EXE = huge.exe

# 本次构建要生成的lib
LIB =

# 本次构建所依赖的头文件路径 
INCLUDE_DIRS = \
$(ROOT)/code/foo/inc \
$(ROOT)/code/bar/inc

# 本次构建所依赖的库 			   
LINK_LIBS = \
foo \
bar

# now begin
include $(ROOT)/build/make.rule