# 本次构建要生成的exe文件
EXE = pja.exe

# 本次构建要生成的lib
LIB = 

# 本次构建所依赖的头文件路径 
INCLUDE_DIRS = $(ROOT)/inc

# 本次构建所依赖的库 			   
LINK_LIBS = pja

# now begin
include $(ROOT)/build/make.rule

#lall:
#	gcc -I/cygdrive/f/mygit/notes/example/makefile/proj_a/inc -o pja_main.o -c pja_main.c
#	gcc -L/cygdrive/f/mygit/notes/example/makefile/proj_a/build/objs -o pja.exe pja_main.o -lpja