# 本次构建要生成的exe文件
EXE =

# 本次构建要生成的lib
LIB =

# 中间文件存放路径
OBJS_DIR=$(ROOT)/build/exe_ut

# 本次构建所依赖的头文件路径(公共头文件路径在总的makefile中定义) 
INCLUDE_DIRS =

# 本次构建所依赖的库 			   
LINK_LIBS = 

# now begin
include $(ROOT)/build/make.rule