/*
---->定义
信号是软件中断，每个信号都有一个名字(以SIG开头),信号都被定义为正整数，不存在编号为0的信号。
信号可以
a:由一个进程发给另外一个进程(或自身)
b:由内核发给某个进程
每个信号都有一个与之关联的处理(disposition),也称为行为(action).信号的处置有三种选择
1 捕获
2 忽略 SIG_IGN
3 默认处理 


Program Start-Up
When a program is executed, the status of all signals is either default or ignore.
Normally,all signals are set to their default action, unless the process that calls exec is
ignoring the signal. Specifically,the exec functions change the disposition of any
signals being caught to their default action and leave the status of all other signals
alone. (Naturally,asignal that is being caught by a process that calls exec cannot be
caught by the same function in the new program, since the address of the signal catching function in the caller probably has no meaning in the new program file that is
executed.)
Process Creation
When a process calls fork,the child inherits the parent’s signal dispositions. Here,
since the child starts off with a copy of the parent’s memory image, the address of a
signal-catching function has meaning in the child.
*/

/*This signal is generated by the terminal driver when we press the interrupt key (often DELETE or Control-C). This signal is 
sent to all processes in the foreground process group. This signal is often used to terminate a runaway program, especially 
when it’s generating a lot of unwanted output on the screen.*/
#define SIGINT 

/*This is a user-defined signal, for use in application programs.*/
#define SIGUSR1

/*This is another user-defined signal,similar to SIGUSR1,for use in application programs.*/
#define SIGUSR2 

/*This signal indicates an implementation-defined  hardwarefault.Implementations usually generate this signal on certain types of memory faults
  如果访问映射区的某个部分,而在访问时这一部分实际上已经不存在，则产生SIGBUS信号*/
#define SIGBUS

/*the process has made an invalid memory reference (which is usually a sign that the program has a bug, such as dereferencing an uninitialized pointer).
The name SEGV stands for ‘‘segmentation violation.’’*/
#define SIGSEGV 

#define SIGPIPE /*If  we  write  to  a  pipeline  but  the  reader  has  terminated, SIGPIPEis
generated.  Wedescribe  pipes  in  Section  15.2. This  signal  is  also
generated when a process writes to a socket of typeSOCK_STREAMthat
is no longer connected. We  describe sockets in Chapter 16.*/

#define SIGTERM /*This is the termination signal sent by the kill(1) command by default.
Because it can be caught by applications, using SIGTERM gives programs
a chance  to  terminate  gracefully  by  cleaning  up  before exiting  (in
contrast to SIGKILL,which can’t be caught or ignored).*/

