/*******************************************************************************
---->定义
信号是软件中断。信号提供了一种处理异步事件的方法，例如，终端用户键入终端键，则会
通过信号机制停止一个程序。每个信号都有一个名字(以SIG开头),信号都被定义为正整数，
不存在编号为0的信号。

信号可以:
a:由一个进程发给另外一个进程(或自身)
b:由内核发给某个进程
每个信号都有一个与之关联的处理(disposition),也称为行为(action).信号的处置有三种选择
1 捕获
2 忽略 SIG_IGN
3 默认处理 

产生信号的条件:
1 某些特定按键，引发终端产生信号。例如Ctrl+C通常产生中断信号(SIGINT)
2 硬件异常产生信号:These conditions are usually detected by the hardware, and the
  kernel is notified. The kernel then generates the appropriate signal for the
  process that was running at the time the condition occurred. For example,SIGSEGV 
  is generated for a process that executes an invalid memory reference.
3 kill命令
4 软件条件:Software conditions can generate signals when a process should be 
  notified of various events. These aren't hardware-generated conditions (as is 
  the divideby-0 condition), but software conditions. Examples are SIGURG 
  (generated when out-of-band data arrives over a network connection), SIGPIPE 
  (generated when a process writes to a pipe that has no reader), and SIGALRM 
  (generated when an alarm clock set by the process expires).

Program Start-Up
When a program is executed, the status of all signals is either default or ignore.
Normally,all signals are set to their default action, unless the process that 
calls exec is ignoring the signal. Specifically,the exec functions change the 
disposition of any signals being caught to their default action and leave the 
status of all other signals alone. (Naturally,asignal that is being caught by 
a process that calls exec cannot be caught by the same function in the new program, 
since the address of the signal catching function in the caller probably has no 
meaning in the new program file that is executed.)

Process Creation
When a process calls fork,the child inherits the parent's signal dispositions. 
Here,since the child starts off with a copy of the parent’s memory image, the 
address of a signal-catching function has meaning in the child.
*/


#define SIGINT /*This signal is generated by the terminal driver when we press 
the interrupt key (often DELETE or Control-C). This signal is  sent to all processes 
in the foreground process group. This signal is often used to terminate a runaway
program, especially when it's generating a lot of unwanted output on the screen.*/
#define SIGUSR1 /*This is a user-defined signal, for use in application programs.*/
#define SIGUSR2 /*This is another user-defined signal,similar to SIGUSR1,for use 
in application programs.*/
#define SIGBUS /*This signal indicates an implementation-defined  hardware fault.
Implementations usually generate this signal on certain types of memory faults
如果访问映射区的某个部分,而在访问时这一部分实际上已经不存在，则产生SIGBUS信号*/
#define SIGSEGV /*the process has made an invalid memory reference (which is 
usually a sign that the program has a bug, such as dereferencing an uninitialized 
pointer).The name SEGV stands for "segmentation violation."*/
#define SIGPIPE /*If we write to a pipeline but the reader has terminated,SIGPIPE 
is generated.This signal is also generated when a process writes to a socket of 
type SOCK_STREAM that is no longer connected.*/
#define SIGTERM /*This is the termination signal sent by the kill(1) command by 
default.Because it can be caught by applications, using SIGTERM gives programs
a chance to terminate gracefully by cleaning up before exiting  (in contrast to 
SIGKILL,which can't be caught or ignored).*/

